language: java
dist: xenial
sudo: true
before_install:
  - sudo add-apt-repository http://packages.cor-lab.de/ubuntu/
  - wget -q http://packages.cor-lab.de/keys/cor-lab.asc -O- | sudo apt-key add -
  - sudo apt-get update -q
  - sudo apt-get install spread
  - ./mvnprep.sh
jdk:
  - openjdk8
  - openjdk10
  - openjdk11
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.m2
